### ISSUE TITLE
pppb2b

### ISSUE THREAD

**Issue by leochan-coder** [xdinav/BDS-3-PPP-B2b_IMU_LiDAR#1]

**Comment by xdinav** [comment]
Sorry, I didn't see your email. I checked it again just now and forgot to add BDS-3 data. I will upload it in a few days



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/11/2024 21:20 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [xdinav/BDS-3-PPP-B2b_IMU_LiDAR] pppb2b (Issue #1) |

Closed #1 as completed.

**Comment by xdinav** [comment]
Sorry, I didn't see your email. I checked it again just now and forgot to add BDS-3 data. I will upload it in a few days
---- Replied Message ----
| From | ***@***.***> |
| Date | 09/11/2024 21:20 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [xdinav/BDS-3-PPP-B2b_IMU_LiDAR] pppb2b (Issue #1) |

Closed #1 as completed.

**Comment by xdinav** [comment]
The dataset has been updated, please download it again.



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/11/2024 21:20 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [xdinav/BDS-3-PPP-B2b_IMU_LiDAR] pppb2b (Issue #1) |

Closed #1 as completed.
